"""empty message

Revision ID: 481632bd632a
Revises: 
Create Date: 2024-07-26 00:37:20.999811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481632bd632a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('displayname', sa.String(length=128), nullable=True),
    sa.Column('bio', sa.String(length=256), nullable=True),
    sa.Column('icon', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='dissscord'
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('displayname', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=256), nullable=True),
    sa.Column('desc', sa.String(length=512), nullable=True),
    sa.Column('banner', sa.String(length=256), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['dissscord.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dissscord'
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('displayname', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['dissscord.servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dissscord'
    )
    op.create_table('server_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['dissscord.servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dissscord.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'server_id'),
    schema='dissscord'
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['dissscord.users.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['dissscord.channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dissscord'
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['dissscord.users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['dissscord.messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dissscord'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions', schema='dissscord')
    op.drop_table('messages', schema='dissscord')
    op.drop_table('server_users', schema='dissscord')
    op.drop_table('channels', schema='dissscord')
    op.drop_table('servers', schema='dissscord')
    op.drop_table('users', schema='dissscord')
    # ### end Alembic commands ###
